import { Inter } from "next/font/google";
import "./globals.css";
import Header from "./_components/Header";
import { ClerkProvider } from "@clerk/nextjs";
import { Toaster } from "../components/ui/sonner";



const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "AI form builder",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
      <html lang="en" className="bg-white text-neutral-900" >
        <body className={inter.className}>
          <Header/>  
          <Toaster/>
          {children}
        </body>
      </html>
    </ClerkProvider>
  );
}
